name: Caching

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Do cache
      id: my-cache
      uses: actions/cache@v3
      with:
        path: dir-i-need-to-cache
        key: my-cache-key

    - name: This step is cached
      if: steps.my-cache.outputs.cache-hit != 'true'
      run: echo random-string > ./dir-i-need-to-cache/random-file-name.txt && echo "hi from cached step"

    - name: This step expects needed stuff is cached and use it right away
      run: cat ./dir-i-need-to-cache/random-file-name.txt && echo "it works!"
